### ISSUE TITLE
Graphite-API returns 500

### ISSUE THREAD

**Issue by szop85** [brutasse/graphite-cyanite#14]
Hello guys,

I have to be honest: I don't know what is causing this problem, so I'm starting here and hope to get a hint or wink into the right direction. My setup look's as following:

Cassandra 2.2
Graphite-API 1.0.1
Cyanite 0.4.5 (pip install cyanite) and also pyr/cynite

```
wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /usr/bin/lein && chmod 755 /usr/bin/lein && /usr/bin/lein && cd /tmp && git clone https://github.com/pyr/cyanite && cd /tmp/cyanite && /usr/bin/lein uberjar
```
Collectd 5.5
Grafana 2.2

```
vim /etc/graphite-api.yaml

cyanite:
  urls:
    - http://127.0.0.1:8080
finders:
  - cyanite.CyaniteFinder
```

```
/etc/cyanite.yaml

engine:
  rules:
    'web.*\.cpu': [ "5s:1h", "30s:1d" ]
    default: [ "5s:1h" ]
api:
  port: 8080
input:
  - type: carbon
    port: 2003
  - type: pickle
    port: 2004
index:
  type: memory
store:
  cluster: 'localhost'
  keyspace: 'metric'
logging:
  level: info
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"
```

netstat is showing all ports that I need:

```
Active Internet connections (only servers)                                                                                                                                                                                                                                                                                                                         [10/1820]
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:43731         0.0.0.0:*               LISTEN      7348/java
tcp        0      0 127.0.0.1:7000          0.0.0.0:*               LISTEN      7348/java
tcp        0      0 127.0.0.1:7199          0.0.0.0:*               LISTEN      7348/java
tcp        0      0 0.0.0.0:48360           0.0.0.0:*               LISTEN      14350/beam.smp
tcp6       0      0 :::8013                 :::*                    LISTEN      16040/apache2
tcp6       0      0 :::8080                 :::*                    LISTEN      16784/java
tcp6       0      0 :::80                   :::*                    LISTEN      16040/apache2
tcp6       0      0 :::4369                 :::*                    LISTEN      14253/epmd
tcp6       0      0 127.0.0.1:9042          :::*                    LISTEN      7348/java
tcp6       0      0 127.0.0.1:2003          :::*                    LISTEN      1448/java
tcp6       0      0 127.0.0.1:2004          :::*                    LISTEN      1448/java
tcp6       0      0 :::3000                 :::*                    LISTEN      20542/grafana-serve
```

My tests look as following:

I'm curling the Graphite-API port on 8013, to get all metrics. Of course the Cassandra DB is empty at the beginning:

![screen shot 2015-09-30 at 14 38 07](https://cloud.githubusercontent.com/assets/2103595/10193047/e9c85178-6780-11e5-97a4-a2527e2bd9ea.png)

I'm just getting an [] back. After starting the collector (collectd), my curl's are producing a 500 in the apache access logs and I'm not able to query for data:

![screen shot 2015-09-30 at 14 48 55](https://cloud.githubusercontent.com/assets/2103595/10193300/6fe6b51e-6782-11e5-9a3b-570f5db27075.png)

Any ideas on that?

Cheers,
Szop
